name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [20, 24]
        exclude:
          - os: ubuntu
            node-version: 24
          - os: windows
            node-version: 20

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    steps:
      - uses: actions/checkout@v6

      - name: Use Node ${{ matrix.node-version }}.x
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}.x

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: rush lint
        run: node common/scripts/install-run-rush.js lint

      - name: rush test
        run: node common/scripts/install-run-rush.js test

      - name: rush regen-ruleindex
        run: node common/scripts/install-run-rush.js regen-ruleindex
